### ISSUE TITLE
handle_action(\3) seems to turn emoji's into random characters

### ISSUE THREAD

**Issue by treuks** [ryanwinchester/tmi.ex#14]
As the title is self-explanatory, I will immediately provide some code.

```elixir
  def handle_message(message, sender, chat) do
    if sender == "treuks" and String.trim(message) == "pajaS \u{1F6A8} ALERT" do
      say(chat, "xd")
    end
    Logger.debug("Message in #{chat} from #{sender}: #{message}")
  end

  def handle_action(message, sender, chat) do
    # if sender == "treuks" and String.trim(message) == "pajaS \u{1F6A8} ALERT" do
    #   say(chat, "xd")
    # end
    Logger.debug("Action in #{chat} from #{sender}: #{message}")
  end
```
Now, what this code is supposed to do, is that if it detects a message from a person, who, in this case, is me, and it contains "pajaS :rotating_light: ALERT", then it should do whatever it should do. Pretty self-explanatory right?

However, if I will provide some logs, what ends up happening is this.

```elixir
07:02:23.992 [debug] Message in #treuks from treuks: pajaS 🚨 ALERT
 
07:02:23.993 [debug] [MessageServer] [treuks] SENT msg: xd
 
07:02:25.494 [debug] [MessageServer] [treuks] no more messages to send: PAUSED
 
07:02:28.672 [debug] Action in #treuks from treuks: pajaS ð¨ ALERT
```
(Looks like this in chat)
![image](https://user-images.githubusercontent.com/18615981/169634731-58c6b821-2cec-45fd-a4fa-f89d364e71b3.png)

As you can see, for some reason, the same exact emoji, in the same exact syntax, and with the same exact logging function, produces a different output. It would be much appreciated, if you could provide an explanation, or a possible fix/workaround for this.

**Comment by ryanwinchester** [comment]
I fixed an issue where `handle_action` wasn't being applied properly and bumped version to `0.6.1` with the fix.

You will need to implement `handle_action/4` instead of `handle_action/3`, as well as make sure you are passing in all the twitch IRC capabilities if you are adding them to config.

Fixed in a19f8e33c4906427809b3d1df5aaa90b687ca682
