### ISSUE TITLE
Provide a way to override `@default_message_rate_ms`

### ISSUE THREAD

**Issue by moniquelive** [ryanwinchester/tmi.ex#15]
I'd like to have the choice do tweak the speed my bot delivers messages to my channel.
Currently 1500 ms is unbearable.

https://github.com/ryanwinchester/tmi.ex/blob/main/lib/tmi/channel_server.ex#L33

TIA

**Comment by ryanwinchester** [comment]
I plan on changing this to better reflect the rate limits based on if the bot is a broadcaster account, verified bot, or not, based on the actual rate limits. For now, it is just conservatively set to prevent from hitting the rate limits for the worst case...

https://dev.twitch.tv/docs/irc#rate-limits

If you hit the rate limit with the bot, then your bot will be ignored by Twitch **for 30 minutes**.

**Comment by ryanwinchester** [comment]
In [2a8c4bc](https://github.com/ryanwinchester/tmi.ex/commit/2a8c4bc97baffe0cf3472ced27054fa63fc5631a) I added a different message rate for when the bot is a moderator, which you define yourself in config.

From readme example, see the `mod_channels` option:

```elixir
config :my_app,
  bots: [
    [
      bot: MyApp.Bot,
      user: "myappbot",
      pass: "oauth:myappbotpassword",
      channels: ["mychannel", "foo"],
      mod_channels: ["mychannel"],
      debug: false
    ]
  ]
```
