### ISSUE TITLE
Dynamically joining and leaving channels

### ISSUE THREAD

**Issue by talk2MeGooseman** [ryanwinchester/tmi.ex#8]
Hi @ryanwinchester, thanks for your hard work and sharing your Twitch IRC library. I am wondering if you have any advice on getting an already running bot to smoothly join and leave channels? I tried coming up with my own solutions but it resulted in failure (probably because of my limited knowledge). Any advice on what I am doing is even possible right now would be appreciated.

**Comment by ryanwinchester** [comment]
@talk2MeGooseman I need to add the `join` function to `TMI`. https://github.com/ryanwinchester/tmi.ex/blob/main/lib/tmi.ex#L26

It will dispatch a message to ChannelServer which can dynamically join channels, but it is rate-limited because Twitch rate-limits channel joins.

**Comment by ryanwinchester** [comment]
Available in `v0.5.1`

```elixir
iex> MyBot.join("channel")
iex> MyBot.part("channel")
```

**Comment by talk2MeGooseman** [comment]
Awesome, thanks for the information and quick turnaround. Right now I am actively using your package for my twitch extension Stream Closed Captioner to send reminder messages to the chat with more complex ideas in the future, and this addition will fuel that idea.

I got lucky that sending messages directly to the chat doesn't actually require joining the chat.
